#!/bin/env sh

cat << EOF > hsctrl2gnome.desktop
[Desktop Entry]
Name=hsctrl2gnome
Comment=Adds a battery percentage panel to your gnome top bar
GenericName=hsctrl2gnome
Exec=/usr/local/bin/hsctrl2gnome
Type=Application
Path=/usr/local/bin
EOF

sudo cp hsctrl2gnome.py /usr/local/bin/hsctrl2gnome
cp hsctrl2gnome.desktop $HOME/.config/autostart/
